package com.qc.tra_cuu_vi_pham.database;

import android.content.Context;

import java.util.List;

public class addDatabase  {
    private Loi_vi_pham loi_vi_pham = new Loi_vi_pham();
    private DatabaseHandler databaseHandler;
    private Context context;
    public  addDatabase(Context context)
    {
        this.context = context;
        databaseHandler = new DatabaseHandler(context);
    }
    public List<Loi_vi_pham> getLoi(String phuongtien, int id_loi){
        return  databaseHandler.getLoi_vi_pham(phuongtien,id_loi);
    }
    public void setLoi_vi_pham_xemay() {
        loi_vi_pham.setID(1);
        loi_vi_pham.setID_Nhom_Loi(1);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Điều khiển xe đi không đúng chiều, phần đường, làn đường");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dieu khien xe di khong dung chieu,phan duong, lan duong");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 2-4 tháng");
        loi_vi_pham.setCT_Loi("Điều khiển xe không đi bên phải theo chiều đi của mình; đi không đúng phần đường,làn đường quy định hoặc điều khiển xe đi trên hè phố,trừ trường hợp điều khiển xe đi qua hè phố để vào nhà");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(2);
        loi_vi_pham.setID_Nhom_Loi(1);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Dừng, đỗ xe trong hầm đường bộ sai quy định");
        loi_vi_pham.setMuc_Phat("500.000-1.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung, do xe trong ham duong bo sai quy dinh");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 2-4 tháng");
        loi_vi_pham.setCT_Loi("Dừng xe, đỗ xe trong hầm đường bộ không đúng nơi quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(3);
        loi_vi_pham.setID_Nhom_Loi(2);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không chấp hành biển báo, vạch kẻ đường");
        loi_vi_pham.setMuc_Phat("60.000-80.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong chap hanh bien bao, vach ke duong");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không chấp hành hiệu lệnh, chỉ dẫn của biển báo hiệu, vạch kẻ đường.");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(4);
        loi_vi_pham.setID_Nhom_Loi(2);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không chấp hành hiệu lệnh đèn giao thông( đèn đỏ,đèn vàng))");
        loi_vi_pham.setMuc_Phat("800.000-1.200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong chap hanh hieu lenh den giao thong(den do,den vang)");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 1-3 tháng. Tăng lên 2-4 tháng nếu gây tai nạn");
        loi_vi_pham.setCT_Loi("Không chấp hành hiệu lệnh của đèn tín hiệu giao thông");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(5);
        loi_vi_pham.setID_Nhom_Loi(2);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Đi vào đường cấm, đi ngược chiều");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Di vao duong cam, di nguoc chieu");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 1-3 tháng. Tăng lên 2-4 tháng nếu gây tai nạn");
        loi_vi_pham.setCT_Loi("Đi vào đường cấm, khu vực cấm; đi ngược chiều của đường một chiều, đi ngược chiều trên đường có biển “Cấm đi ngược chiều”, trừ trường hợp xe ưu tiên đang đi làm nhiệm vụ khẩn cấp theo quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(6);
        loi_vi_pham.setID_Nhom_Loi(2);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Điều khiển xe máy vào cao tốc");
        loi_vi_pham.setMuc_Phat("500.000-1.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dieu khien xe may vao cao toc");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 1-3 tháng. Tăng lên 2-4 tháng nếu gây tai nạn");
        loi_vi_pham.setCT_Loi("Điều khiển xe đi vào đường cao tốc, trừ xe phục vụ việc quản lý, bảo trì đường cao tốc");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(7);
        loi_vi_pham.setID_Nhom_Loi(2);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Vượt xe trong trường hợp cấm vượt");
        loi_vi_pham.setMuc_Phat("500.000-1.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Vuot xe trong truong hop cam vuot");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Vượt xe trong những trường hợp cấm vượt, trừ các hành vi vượt bên phải trong các trường hợp không được phép");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(8);
        loi_vi_pham.setID_Nhom_Loi(2);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Dừng, đỗ xe trong hầm đường bộ sai quy định");
        loi_vi_pham.setMuc_Phat("500.000-1.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung, do xe trong ham duong bo sai quy dinh");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 2-4 tháng");
        loi_vi_pham.setCT_Loi("Dừng xe, đỗ xe trong hầm đường bộ không đúng nơi quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(9);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không giữ khoảng cách");
        loi_vi_pham.setMuc_Phat("60.000-80.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong giu khoang cach");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không giữ khoảng cách an toàn để xảy ra va chạm với xe chạy liền trước hoặc không giữ khoảng cách theo quy định của biển báo hiệu");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(10);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không giảm tốc độ khi đi ra từ ngõ");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong giam toc do khi di ra tu ngo");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không giảm tốc độ hoặc không nhường đường khi điều khiển xe chạy từ trong ngõ, đường nhánh ra đường chính");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(11);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Chạy quá tốc độ 5-10 km/h");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chay qua toc do 5-10 km/h");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Điều khiển xe chạy quá tốc độ quy định từ 05 km/h đến dưới 10 km/h");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(12);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Đi chậm nhưng không đi về bên phải");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Di cham nhung khong di ve ben phai");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Điều khiển xe chạy tốc độ thấp mà không đi bên phải phần đường xe chạy gây cản trở giao thông");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(13);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Chạy dưới tốc độ tối thiểu");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chay duoi toc do toi thieu");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Điều khiển xe chạy dưới tốc độ tối thiểu trên những đoạn đường bộ có quy định tốc độ tối thiểu cho phép");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(14);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Chạy quá tốc độ 10-20km");
        loi_vi_pham.setMuc_Phat("500.000-1.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chay qua toc do 10-20km");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Điều khiển xe chạy quá tốc độ quy định từ 10 km/h đến 20 km/h");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(15);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Điều khiển xe chạy quá tốc độ gây tai nạn");
        loi_vi_pham.setMuc_Phat("2.000.000-3.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dieu khien xe chay qua toc do gay tai nan");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 2-4 tháng");
        loi_vi_pham.setCT_Loi("Không chú ý quan sát, điều khiển xe chạy quá tốc độ quy định gây tai nạn giao thông; vượt xe hoặc chuyển làn đường trái quy định gây tai nạn giao thông");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(16);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Chạy quá tốc độ trên 20 km/h");
        loi_vi_pham.setMuc_Phat("3.000.000-4.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chay qua toc do tren 20 km/h");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 1-3 tháng");
        loi_vi_pham.setCT_Loi("Điều khiển xe chạy quá tốc độ quy định trên 20 km/h");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(17);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Điều khiển xe thành nhóm chạy quá tốc độ");
        loi_vi_pham.setMuc_Phat("5.000.000-7.000.000 hoặc 10.000.000 - 14.000.000 (nếu gây tai nạn) vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dieu khien xe thanh nhom chay qua toc do");
        loi_vi_pham.setHp_BS("Tạm giữ phương tiện, giấy tờ. Nếu vi phạm nhiều lần, gây tai nạn, tước quyền sử dụng Giấy phép lái xe từ 3-5 tháng, tịch thu phương tiện.");
        loi_vi_pham.setCT_Loi("Điều khiển xe thành nhóm từ hai xe trở lên chạy quá tốc độ quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(18);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Dừng, đỗ trên phần đường xe chạy");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung, do tren phan duong xe chay");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Dừng xe, đỗ xe trên phần đường xe chạy ở đoạn đường ngoài đô thị nơi có lề đường");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(19);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Dừng, đỗ ở lòng đường đô thị");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung, do o long duong do thi");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Chuyển hướng không nhường quyền đi trước cho: Người đi bộ, xe lăn của người khuyết tật qua đường tại nơi có vạch kẻ đường dành cho người đi bộ; xe thô sơ đang đi trên phần đường dành cho xe thô sơ");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(20);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Dừng đỗ xe sai quy định");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung do xe sai quy dinh");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Dừng đỗ xe sai quy định ở Điểm b Khoản 2, Điểm b Khoản 3 Điều 48 Nghị định này");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(21);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Dừng, đỗ xe trên cầu");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung, do xe tren cau");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Dừng xe, đỗ xe trên cầu");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(22);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không có báo hiệu xin vượt trước khi vượt");
        loi_vi_pham.setMuc_Phat("60.000-80.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong co bao hieu xin vuot truoc khi vuot");
        loi_vi_pham.setHp_BS("Không");
        loi_vi_pham.setCT_Loi("Không có báo hiệu xin vượt trước khi vượt");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(23);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không nhường quyền cho người ưu tiên");
        loi_vi_pham.setMuc_Phat("60.000-80.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong nhuong quyen cho nguoi uu tien");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Chuyển hướng không nhường quyền đi trước cho: Người đi bộ, xe lăn của người khuyết tật qua đường tại nơi có vạch kẻ đường dành cho người đi bộ; xe thô sơ đang đi trên phần đường dành cho xe thô sơ");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(24);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Chuyển hướng không nhường đường");
        loi_vi_pham.setMuc_Phat("60.000-80.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chuyen huong khong nhuong duong");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Chuyển hướng không nhường đường cho: Các xe đi ngược chiều; người đi bộ, xe lăn của người khuyết tật đang qua đường tại nơi Không có vạch kẻ đường cho người đi bộ");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(25);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Lùi xe Không có tín hiệu");
        loi_vi_pham.setMuc_Phat("60.000-80.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Lui xe khong co tin hieu");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Lùi xe môtô ba bánh không quan sát hoặc Không có tín hiệu báo trước");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(26);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không nhường đường tại nơi giao nhau");
        loi_vi_pham.setMuc_Phat("60.000-80.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong nhuong duong tai noi giao nhau");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không tuân thủ các quy định về nhường đường tại nơi đường giao nhau, trừ các hành vi vi phạm quy định tại các Điểm d Khoản 2, Điểm b Khoản 3 Điều này.");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(27);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Chuyển làn đường trái phép");
        loi_vi_pham.setMuc_Phat("80.000-100.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chuyen lan duong trai phep");
        loi_vi_pham.setHp_BS("Không");
        loi_vi_pham.setCT_Loi("Chuyển làn đường không đúng nơi được phép hoặc Không có tín hiệu báo trước");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(28);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không nhường đường cho xe xin vượt");
        loi_vi_pham.setMuc_Phat("80.000-100.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong nhuong duong cho xe xin vuot");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không nhường đường cho xe xin vượt khi có đủ điều kiện an toàn; không nhường đường cho xe đi trên đường ưu tiên, đường chính từ bất kỳ hướng nào tới tại nơi đường giao nhau");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(29);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không nhường đường cho xe ngược chiều");
        loi_vi_pham.setMuc_Phat("80.000-100.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong nhuong duong cho xe nguoc chieu");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Tránh xe không đúng quy định; không nhường đường cho xe đi ngược chiều theo quy định tại nơi đường hẹp, đường dốc, nơi có chướng ngại vật");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(30);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Quay đầu xe tại nơi cấm");
        loi_vi_pham.setMuc_Phat("80.000-100.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Quay dau xe tai noi cam");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Quay đầu xe tại nơi cấm quay đầu xe");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(31);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Chuyển hướng không giảm tốc độ hoặc Không có tín hiệu báo chuyển hướng(xi nhan)");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chuyen huong khong giam toc do hoac khong co tin hieu bao chuyen huong");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe 2-4 tháng");
        loi_vi_pham.setCT_Loi("Chuyển hướng không giảm tốc độ hoặc Không có tín hiệu báo hướng rẽ (trừ trường hợp điều khiển xe đi theo hướng cong của đoạn đường bộ ở nơi đường không giao nhau cùng mức)");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(32);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Vượt phải không được phép");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Vuot phai khong duoc phep");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Vượt bên phải trong các trường hợp không được phép");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(33);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không nhường đường, gây cản trở xe ưu tiên");
        loi_vi_pham.setMuc_Phat("500.000-1.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong nhuong duong, gay can tro xe uu tien");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 2-4 tháng");
        loi_vi_pham.setCT_Loi("Không nhường đường hoặc gây cản trở xe được quyền ưu tiên đang phát tín hiệu ưu tiên đi làm nhiệm vụ");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(34);
        loi_vi_pham.setID_Nhom_Loi(6);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Trong máu, hơi thở có nồng độ cồn 0.25ml/lit khí thở");
        loi_vi_pham.setMuc_Phat("1.000.000-2.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Trong mau, hoi tho co nong do con 0.25ml/lit khi tho");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 2-4 tháng");
        loi_vi_pham.setCT_Loi("Người điều khiển xe trên đường mà trong máu hoặc hơi thở có nồng độ cồn vượt quá 50 miligam đến 80 miligam/100 mililít máu hoặc vượt quá 0,25 miligam đến 0,4 miligam/1 lít khí thở.");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(35);
        loi_vi_pham.setID_Nhom_Loi(6);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không chấp hành yêu cầu kiểm tra ma túy, nồng độ cồn");
        loi_vi_pham.setMuc_Phat("3.000.000-4.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong chap hanh yeu cau kiem tra ma tuy, nong do con");
        loi_vi_pham.setHp_BS("Tạm giữ phương tiện, giấy tờ. tước quyền sử dụng Giấy phép lái xe từ 03 tháng đến 05 tháng.");
        loi_vi_pham.setCT_Loi("Không chấp hành yêu cầu kiểm tra về chất ma túy, nồng độ cồn của người thi hành công vụ");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(36);
        loi_vi_pham.setID_Nhom_Loi(6);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Trong máu, hơi thở có nồng độ cồn 0.40");
        loi_vi_pham.setMuc_Phat("3.000.000-4.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Trong mau, hoi tho co nong do con 0.40");
        loi_vi_pham.setHp_BS("Tạm giữ phương tiện, giấy tờ. tước quyền sử dụng Giấy phép lái xe từ 03 tháng đến 05 tháng.");
        loi_vi_pham.setCT_Loi("Điều khiển xe trên đường mà trong máu hoặc hơi thở có nồng độ cồn vượt quá 80 miligam/100 mililít máu hoặc vượt quá 0,4 miligam/1 lít khí thở");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(37);
        loi_vi_pham.setID_Nhom_Loi(6);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Điều khiển xe mà trong cơ thể có chất ma túy");
        loi_vi_pham.setMuc_Phat("3.000.000-4.000.000 (trong trường hợp Không có Giấy phép lái xe hoặc có nhưng đang bị tước quyền sử dụng Giấy phép lái xe) vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dieu khien xe ma trong co the co chat ma tuy");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 22-24 tháng (trong trường hợp có Giấy phép lái xe) hoặc phạt tiền từ 3.000.000 - 4.000.000 đồng (trong trường hợp Không có Giấy phép lái xe hoặc có nhưng đang bị tước quyền sử dụng Giấy phép lái xe)");
        loi_vi_pham.setCT_Loi("Điều khiển xe trên đường mà trong cơ thể có chất ma túy.");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(38);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Sử dụng đèn sai");
        loi_vi_pham.setMuc_Phat("60.000-80.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Su dung den sai");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Sử dụng đèn chiếu xa khi tránh xe đi ngược chiều");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(39);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Chở người ngồi trên xe sử dụng ô (dù)");
        loi_vi_pham.setMuc_Phat("60.000-80.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Cho nguoi ngoi tren xe su dung o (du)");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Chở người ngồi trên xe sử dụng ô (dù);");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(40);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Chạy xe dàn hàng ngang");
        loi_vi_pham.setMuc_Phat("80.000-100.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chay xe dan hang ngang");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Điều khiển xe chạy dàn hàng ngang từ 3 (ba) xe trở lên");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(41);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Sử dụng đèn chiếu sáng sai");
        loi_vi_pham.setMuc_Phat("80.000-100.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Su dung den chieu sang sai");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không sử dụng đèn chiếu sáng trong thời gian từ 19 giờ ngày hôm trước đến 05 giờ ngày hôm sau hoặc khi sương mù, thời tiết xấu hạn chế tầm nhìn");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(42);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Sử dụng đèn và còi trong khu vực cấm");
        loi_vi_pham.setMuc_Phat("80.000-100.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Su dung den va coi trong khu vuc cam");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Bấm còi trong thời gian từ 22 giờ ngày hôm trước đến 05 giờ ngày hôm sau, sử dụng đèn chiếu xa trong đô thị, khu đông dân cư, trừ các xe ưu tiên đang đi làm nhiệm vụ theo quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(43);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Sử dụng tín hiệu ưu tiên trái phép");
        loi_vi_pham.setMuc_Phat("80.000-100.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Su dung tin hieu uu tien trai phep");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Xe được quyền ưu tiên lắp đặt, sử dụng thiết bị phát tín hiệu ưu tiên không đúng quy định hoặc sử dụng thiết bị phát tín hiệu ưu tiên mà Không có Giấy phép của cơ quan có thẩm quyền cấp hoặc có Giấy phép của cơ quan có thẩm quyền cấp nhưng không còn giá trị sử dụng theo quy định;");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(44);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Bấm còi, rú ga liên tục");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Bam coi, ru ga lien tuc");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Bấm còi, rú ga (nẹt pô) liên tục trong đô thị, khu đông dân cư, trừ các xe ưu tiên đang đi làm nhiệm vụ theo quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(45);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Sử dụng thiếu bị ưu tiên trái phép");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Su dung thieu bi uu tien trai phep");
        loi_vi_pham.setHp_BS("Thu thiết bị, Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Xe không được quyền ưu tiên lắp đặt, sử dụng thiết bị phát tín hiệu của xe được quyền ưu tiên");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(46);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không đội mũ bảo hiểm");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong doi mu bao hiem");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Người điều khiển, người ngồi trên xe không đội “mũ bảo hiểm cho người đi mô tô, xe máy” hoặc đội “mũ bảo hiểm cho người đi mô tô, xe máy” không cài quai đúng quy cách khi tham gia giao thông trên đường bộ");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(47);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Chở người không đội mũ bảo hiểm");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Cho nguoi khong doi mu bao hiem");
        loi_vi_pham.setHp_BS("Không");
        loi_vi_pham.setCT_Loi("Chở người ngồi trên xe không đội “mũ bảo hiểm cho người đi mô tô, xe máy” hoặc đội “mũ bảo hiểm cho người đi mô tô, xe máy” không cài quai đúng quy cách, trừ trường hợp chở người bệnh đi cấp cứu, trẻ em dưới 06 tuổi, áp giải người có hành vi vi phạm pháp luật");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(48);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Chở người quá số lượng quy định");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Cho nguoi qua so luong quy dinh");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Chở theo 02 (hai) người trên xe, trừ trường hợp chở người bệnh đi cấp cứu, trẻ em dưới 14 tuổi, áp giải người có hành vi vi phạm pháp luật");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(49);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Người ngồi sau điều khiển xe");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Nguoi ngoi sau dieu khien xe");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Người ngồi phía sau vòng tay qua người ngồi trước để điều khiển xe, trừ trường hợp chở trẻ em ngồi phía trước");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(50);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Đang lái xe dùng ô (dù), điện thoại");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dang lai xe dung o (du), dien thoai");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Người đang điều khiển xe sử dụng ô (dù), điện thoại di động, thiết bị âm thanh, trừ thiết bị trợ thính");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(51);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Chở ba người trở lên");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Cho ba nguoi tro len");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 1-3 tháng. Tăng lên 2-4 tháng nếu gây tai nạn");
        loi_vi_pham.setCT_Loi("Chở theo ba người trở lên trên xe");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(52);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Điều khiển xe thành đoàn gây cản trở");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dieu khien xe thanh doan gay can tro");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Điều khiển xe thành đoàn gây cản trở giao thông, trừ trường hợp được cơ quan có thẩm quyền cấp phép");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(53);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Điều khiển xe liên quan trực tiếp đến tai nạn mà không dừng lại, tham gia cấp cứu");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dieu khien xe lien quan truc tiep den tai nan ma khong dung lai, tham gia cap cuu");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Điều khiển xe có liên quan trực tiếp đến vụ tai nạn giao thông mà không dừng lại, không giữ nguyên hiện trường, không tham gia cấp cứu người bị nạn, trừ hành vi gây tai nạn giao thông không dừng lại, không giữ nguyên hiện trường, bỏ trốn không đến trình báo với cơ quan có thẩm quyền, không tham gia cấp cứu người bị nạn.");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(54);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Bám kéo đẩy xe khác");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Bam keo day xe khac");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 2-4 tháng");
        loi_vi_pham.setCT_Loi("Người điều khiển xe hoặc người ngồi trên xe bám, kéo, đẩy xe khác, vật khác, dẫn dắt súc vật, mang vác vật cồng kềnh; người được chở trên xe đứng trên yên, giá đèo hàng hoặc ngồi trên tay lái; xếp hàng hóa trên xe vượt quá giới hạn quy định; điều khiển xe kéo theo xe khác, vật khác");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(55);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Chở hàng vượt trọng tải, thiết kế");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Cho hang vuot trong tai, thiet ke");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Chở hàng vượt trọng tải thiết kế được ghi trong Giấy đăng ký xe đối với loại xe có quy định về trọng tải thiết kế");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(56);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không chấp hành hiệu lệnh");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong chap hanh hieu lenh");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 1-3 tháng. Tăng lên 2-4 tháng nếu gây tai nạn");
        loi_vi_pham.setCT_Loi("Không chấp hành hiệu lệnh, hướng dẫn của người điều khiển giao thông hoặc người kiểm soát giao thông");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(57);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không sử dụng đèn khi chạy trong hầm đường bộ");
        loi_vi_pham.setMuc_Phat("500.000-1.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong su dung den khi chay trong ham duong bo");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 1-3 tháng. Tăng lên 2-4 tháng nếu gây tai nạn");
        loi_vi_pham.setCT_Loi("Chạy trong hầm đường bộ không sử dụng đèn chiếu sáng gần; vượt xe trong hầm đường bộ không đúng nơi quy định; quay đầu xe trong hầm đường bộ");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(58);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Dùng chân chống quệt xuống đường");
        loi_vi_pham.setMuc_Phat("2.000.000-3.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung chan chong quet xuong duong");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 1-3 tháng");
        loi_vi_pham.setCT_Loi("Sử dụng chân chống hoặc vật khác quệt xuống đường khi xe đang chạy");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(59);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Gây tai nạn không dừng lại, bỏ trốn");
        loi_vi_pham.setMuc_Phat("2.000.000-3.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Gay tai nan khong dung lai, bo tron");
        loi_vi_pham.setHp_BS("Tước quyền sử dụng Giấy phép lái xe từ 2-4 tháng");
        loi_vi_pham.setCT_Loi("Gây tai nạn giao thông không dừng lại, không giữ nguyên hiện trường, bỏ trốn không đến trình báo với cơ quan có thẩm quyền, không tham gia cấp cứu người bị nạn");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(60);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Điều khiển xe bằng chân, buông tay, ngồi một bên, nằm trên xe");
        loi_vi_pham.setMuc_Phat("5.000.000-7.000.000 hoặc 10.000.000 - 14.000.000 (nếu gây tai nạn)");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dieu khien xe bang chan, buong tay, ngoi mot ben, nam tren xe");
        loi_vi_pham.setHp_BS("Tạm giữ phương tiện, giấy tờ. Nếu vi phạm nhiều lần, gây tai nạn, tước quyền sử dụng Giấy phép lái xe từ 3-5 tháng, tịch thu phương tiện.");
        loi_vi_pham.setCT_Loi("Buông cả hai tay khi đang điều khiển xe; dùng chân điều khiển xe; ngồi về một bên điều khiển xe; nằm trên yên xe điều khiển xe; thay người điều khiển khi xe đang chạy; quay người về phía sau để điều khiển xe hoặc bịt mắt điều khiển xe");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(61);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Lạng lách, đánh võng");
        loi_vi_pham.setMuc_Phat("5.000.000-7.000.000 hoặc 10.000.000 - 14.000.000 (nếu gây tai nạn)");
        loi_vi_pham.setTen_Loi_Ko_Dau("Lang lach, danh vong");
        loi_vi_pham.setHp_BS("Tạm giữ phương tiện, giấy tờ. Nếu vi phạm nhiều lần, gây tai nạn, tước quyền sử dụng Giấy phép lái xe từ 3-5 tháng, tịch thu phương tiện.");
        loi_vi_pham.setCT_Loi("Điều khiển xe lạng lách hoặc đánh võng trên đường bộ trong, ngoài đô thị");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(62);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Điều khiển xe bằng một bánh");
        loi_vi_pham.setMuc_Phat("5.000.000-7.000.000 hoặc 10.000.000 - 14.000.000 (nếu gây tai nạn)");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dieu khien xe bang mot banh");
        loi_vi_pham.setHp_BS("Tạm giữ phương tiện, giấy tờ. Nếu vi phạm nhiều lần, gây tai nạn, tước quyền sử dụng Giấy phép lái xe từ 3-5 tháng, tịch thu phương tiện.");
        loi_vi_pham.setCT_Loi("Điều khiển xe chạy bằng một bánh đối với xe hai bánh, chạy bằng hai bánh đối với xe ba bánh");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(63);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không mang GPLX");
        loi_vi_pham.setMuc_Phat("80.000-120.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong mang GPLX");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Không mang giấy phép lái xe");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(64);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không có gGPLX A1");
        loi_vi_pham.setMuc_Phat("800.000-1.200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong co gGPLX A1");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Không có giấy phép lái xe với xe dưới 175 cm3");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(65);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không có GPLX A2");
        loi_vi_pham.setMuc_Phat("4.000.000 - 6.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong co GPLX A2");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Không có giấy phép lái xe với xe từ 175cm3");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(129);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không có hoặc không mang theo giấy chứng nhận bảo hiểm trách nhiệm dân sự của chủ xe cơ giới còn hiệu lực");
        loi_vi_pham.setMuc_Phat("80.000-120.000 vnd");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong co hoac khong mang theo giay chung nhan bao hiem trach nhiem dan su cua chu xe co gioi con hieu luc");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Không mang theo bảo hiểm xe bắc buộc");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(131);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không bật đèn xe( từ 18h-6h hoặc sương mù, thời tiết hạn chế tầm nhìn)");
        loi_vi_pham.setMuc_Phat("80.000-100.000 vnd");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong bat den xe( tu 18h-6h hoac suong mu, thoi tiet han che tam nhin)");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Không bật đèn xe theo quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
    }
    public  void setLoi_vi_pham_oto(){
        loi_vi_pham.setID(66);
        loi_vi_pham.setID_Nhom_Loi(1);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Chuyển làn không đúng nơi, Không có tín hiệu");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chuyen lan khong dung noi, khong co tin hieu");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Chuyển làn đường không đúng nơi cho phép hoặc Không có tín hiệu báo trước");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(67);
        loi_vi_pham.setID_Nhom_Loi(1);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Chạy xe tốc độ thấp không đi về bên phải");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chay xe toc do thap khong di ve ben phai");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Điều khiển xe chạy tốc độ thấp hơn các xe khác đi cùng chiều mà không đi về bên phải phần đường xe chạy, trừ trường hợp các xe khác đi cùng chiều chạy quá tốc độ quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(68);
        loi_vi_pham.setID_Nhom_Loi(1);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Đi vào đường cấm, đi ngược chiều");
        loi_vi_pham.setMuc_Phat("800.000-1.200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Di vao duong cam, di nguoc chieu");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 1-3 tháng, nếu gây tai nạn 2-4 tháng");
        loi_vi_pham.setCT_Loi("Đi vào đường cấm, khu vực cấm; đi ngược chiều của đường một chiều, đi ngược chiều trên đường có biển “Cấm đi ngược chiều”");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(69);
        loi_vi_pham.setID_Nhom_Loi(1);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không đi đúng phần đường, làn đường");
        loi_vi_pham.setMuc_Phat("800.000-1.200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong di dung phan duong, lan duong");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 1-3 tháng, nếu gây tai nạn 2-4 tháng");
        loi_vi_pham.setCT_Loi("Điều khiển xe không đi bên phải theo chiều đi của mình; đi không đúng phần đường hoặc làn đường quy định; điều khiển xe đi qua dải phân cách cứng ở giữa hai phần đường xe chạy; điều khiển xe đi trên hè phố, trừ trường hợp điều khiển xe đi qua hè phố để vào nhà");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(70);
        loi_vi_pham.setID_Nhom_Loi(2);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không chấp hành biển báo, vạch kẻ đường");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong chap hanh bien bao, vach ke duong");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không chấp hành hiệu lệnh, chỉ dẫn của biển báo hiệu, vạch kẻ đường");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(71);
        loi_vi_pham.setID_Nhom_Loi(2);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không tuân thủ đèn giao thông");
        loi_vi_pham.setMuc_Phat("1.200.000 -2.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong tuan thu den giao thong");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn");
        loi_vi_pham.setCT_Loi("Không chấp hành hiệu lệnh của đèn tín hiệu giao thông");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(72);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không giữ khoảng cách an toàn");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong giu khoang cach an toan");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không giữ khoảng cách an toàn để xảy ra va chạm với xe chạy liền trước hoặc không giữ khoảng cách theo quy định của biển báo hiệu “Cự ly tối thiểu giữa hai xe”");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(73);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Chạy quá tốc độ quy định 05-10 km/h");
        loi_vi_pham.setMuc_Phat("600.000-800.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chay qua toc do quy dinh 05-10 km/h");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Điều khiển xe chạy quá tốc độ quy định từ 05 km/h đến dưới 10 km/h");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(74);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Chạy dưới tốc độ tối thiểu");
        loi_vi_pham.setMuc_Phat("800.000-1.200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chay duoi toc do toi thieu");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Điều khiển xe chạy dưới tốc độ tối thiểu trên những đoạn đường bộ có quy định tốc độ tối thiểu cho phép");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(75);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Quá tốc độ 10-20 km/h");
        loi_vi_pham.setMuc_Phat("2.000.000 - 3.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Qua toc do 10-20 km/h");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Điều khiển xe chạy quá tốc độ quy định từ 10 km/h đến 20 km/h.");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(76);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Quá tốc độ 20-35 km/h");
        loi_vi_pham.setMuc_Phat("5.000.000 - 6.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Qua toc do 20-35 km/h");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Điều khiển xe chạy quá tốc độ quy định từ 10 km/h đến 20 km/h.");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(77);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Gây tai nạn vì chạy quá tốc độ, không giữ khoảng cách an toàn, tránh, vượt không đúng quy tắc");
        loi_vi_pham.setMuc_Phat("7.000.000 - 8.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Gay tai nan vi chay qua toc do, khong giu khoang cach an toan, tranh, vuot khong dung quy tac");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng");
        loi_vi_pham.setCT_Loi("Không chú ý quan sát, điều khiển xe chạy quá tốc độ quy định gây tai nạn giao thông; tránh, vượt không đúng quy định gây tai nạn giao thông hoặc không giữ khoảng cách an toàn giữa hai xe theo quy định gây tai nạn giao thông");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(78);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Lạng lách, đánh võng, dùng chân lái xe");
        loi_vi_pham.setMuc_Phat("7.000.000 - 8.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Lang lach, danh vong, dung chan lai xe");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng");
        loi_vi_pham.setCT_Loi("Điều khiển xe lạng lách, đánh võng; chạy quá tốc độ đuổi nhau trên đường bộ; dùng chân điều khiển vô-lăng xe khi xe đang chạy trên đường");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(79);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Quá tốc độ trên 35 km/h");
        loi_vi_pham.setMuc_Phat("7.000.000 - 8.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Qua toc do tren 35 km/h");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng, Tước giấy phép lái xe 3-5 tháng nếu tái vi phạm");
        loi_vi_pham.setCT_Loi("Điều khiển xe chạy quá tốc độ quy định trên 35 km/h");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(80);
        loi_vi_pham.setID_Nhom_Loi(3);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Lạng lách, đánh võng, dùng chân lái xe gây tai nạn");
        loi_vi_pham.setMuc_Phat("18.000.000 - 20.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Lang lach, danh vong, dung chan lai xe gay tai nan");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 3-5 tháng");
        loi_vi_pham.setCT_Loi("Điều khiển xe lạng lách, đánh võng; chạy quá tốc độ đuổi nhau trên đường bộ; dùng chân điều khiển vô lăng xe khi xe đang chạy trên đường mà không chấp hành hiệu lệnh dừng xe của người thi hành công vụ hoặc gây tai nạn giao thông");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(81);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Dừng, đỗ Không có tín hiệu");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung, do khong co tin hieu");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Khi dừng xe, đỗ xe Không có tín hiệu báo cho người điều khiển phương tiện khác biết;");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(82);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Đỗ xe chiếm đường");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Do xe chiem duong");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Khi đỗ xe chiếm một phần đường xe chạy không đặt ngay báo hiệu nguy hiểm theo quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(83);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Dừng, đỗ xe không đúng quy định");
        loi_vi_pham.setMuc_Phat("300.000-800.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung, do xe khong dung quy dinh");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Dừng đỗ xe sai quy định (có 3 trường hợp)");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(84);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Dừng, đỗ xe vi phạm an toàn đường sắt");
        loi_vi_pham.setMuc_Phat("600.000-800.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung, do xe vi pham an toan duong sat");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không tuân thủ các quy định về dừng xe, đỗ xe tại nơi đường bộ giao nhau cùng mức với đường sắt; dừng xe, đỗ xe trong phạm vi an toàn của đường sắt");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(85);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Dừng, đỗ xe vi phạm an toàn đường sắt");
        loi_vi_pham.setMuc_Phat("600.000-800.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung, do xe vi pham an toan duong sat");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông  ");
        loi_vi_pham.setCT_Loi("Đỗ xe không sát theo lề đường, hè phố phía bên phải theo chiều đi hoặc bánh xe gần nhất cách lề đường, hè phố quá 0,25 m; đỗ xe trên đường xe điện, đường dành riêng cho xe buýt; đỗ xe trên miệng cống thoát nước, miệng hầm của đường điện thoại, điện cao thế, chỗ dành riêng cho xe chữa cháy lấy nước; đỗ, để xe ở hè phố trái quy định của pháp luật; đỗ xe nơi có biển “Cấm đỗ xe” hoặc biển “Cấm dừng xe và đỗ xe”");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(86);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Dừng, đỗ xe không đúng cách");
        loi_vi_pham.setMuc_Phat("600.000-800.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung, do xe khong dung cach");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Dừng xe, đỗ xe, quay đầu xe trái quy định gây ùn tắc giao thông");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(87);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Dừng, đỗ, quay đầu xe gây ùn tắc");
        loi_vi_pham.setMuc_Phat("800.000-1.200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung, do, quay dau xe gay un tac");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Dừng xe, đỗ xe trong hầm đường bộ không đúng nơi quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(88);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Dừng xe, đỗ xe trong hầm đường bộ không đúng nơi quy định");
        loi_vi_pham.setMuc_Phat("800.000-1.200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung xe, do xe trong ham duong bo khong dung noi quy dinh");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn");
        loi_vi_pham.setCT_Loi("Không tuân thủ các quy định về dừng xe, đỗ xe trên đường cao tốc; khi dừng xe, đỗ xe trên đường cao tốc không đặt ngay biển báo hiệu nguy hiểm theo quy định.");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(89);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Dừng, đỗ xe trên cao tốc không đúng quy định");
        loi_vi_pham.setMuc_Phat("5.000.000 - 6.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dung, do xe tren cao toc khong dung quy dinh");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Chuyển hướng không nhường quyền đi trước cho: Người đi bộ, xe lăn của người khuyết tật qua đường tại nơi có vạch kẻ đường dành cho người đi bộ; xe thô sơ đang đi trên phần đường dành cho xe thô sơ");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(90);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Chuyển hướng không nhường quyền đi trước");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chuyen huong khong nhuong quyen di truoc");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Chuyển hướng không nhường đường cho: Các xe đi ngược chiều; người đi bộ, xe lăn của người khuyết tật đang qua đường tại nơi Không có vạch kẻ đường cho người đi bộ;");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(91);
        loi_vi_pham.setID_Nhom_Loi(4);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Chuyển hướng không nhường đường");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chuyen huong khong nhuong duong");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không tuân thủ các quy định về nhường đường tại nơi đường bộ giao nhau");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(92);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không nhường đường");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong nhuong duong");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không tuân thủ các quy định về nhường đường tại nơi đường bộ giao nhau");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(93);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không giảm tốc độ và nhường đường khi ra đường chính");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong giam toc do va nhuong duong khi ra duong chinh");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không giảm tốc độ và nhường đường khi điều khiển xe chạy từ trong ngõ, đường nhánh ra đường chính");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(94);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không nhường đường cho xe xin vượt, xe ưu tiên, xe từ đường chính");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong nhuong duong cho xe xin vuot, xe uu tien, xe tu duong chinh");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không nhường đường cho xe xin vượt khi có đủ điều kiện an toàn; không nhường đường cho xe đi trên đường ưu tiên, đường chính từ bất kỳ hướng nào tới tại nơi đường giao nhau");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(95);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Quay đầu xe trong khu dân cư");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Quay dau xe trong khu dan cu");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Quay đầu xe trái quy định trong khu dân cư");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(96);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Quay đầu xe không đúng quy định");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Quay dau xe khong dung quy dinh");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Quay đầu xe ở phần đường dành cho người đi bộ qua đường, trên cầu, đầu cầu, gầm cầu vượt, ngầm, đường hẹp, đường dốc, đoạn đường cong tầm nhìn bị che khuất, nơi có biển báo “Cấm quay đầu xe”");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(97);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Lùi xe nơi không được phép");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Lui xe noi khong duoc phep");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Lùi xe ở đường một chiều, đường có biển “Cấm đi ngược chiều”, khu vực cấm dừng, trên phần đường dành cho người đi bộ qua đường, nơi đường bộ giao nhau, nơi đường bộ giao nhau cùng mức với đường sắt, nơi tầm nhìn bị che khuất; lùi xe không quan sát hoặc Không có tín hiệu báo trước");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(98);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Chuyển hướng không giảm tốc độ hoặc Không có tín hiệu");
        loi_vi_pham.setMuc_Phat("600.000-800.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chuyen huong khong giam toc do hoac khong co tin hieu");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Chuyển hướng không giảm tốc độ hoặc Không có tín hiệu báo hướng rẽ (trừ trường hợp điều khiển xe đi theo hướng cong của đoạn đường bộ ở nơi đường không giao nhau cùng mức)");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(99);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Quay đầu xe nơi giao nhau với đường sắt");
        loi_vi_pham.setMuc_Phat("600.000-800.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Quay dau xe noi giao nhau voi duong sat");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 1-3 tháng, nếu gây tai nạn 2-4 tháng");
        loi_vi_pham.setCT_Loi("Quay đầu xe tại nơi đường bộ giao nhau cùng mức với đường sắt");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(100);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Chạy ở làn dừng khẩn cấp, chuyển làn Không có tín hiệu, lùi, quay đầu xe, không giữ khoảng cách an toàn trên đường cao tốc");
        loi_vi_pham.setMuc_Phat("800.000-1.200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Chay o lan dung khan cap, chuyen lan khong co tin hieu, lui, quay dau xe, khong giu khoang cach an toan tren duong cao toc");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 1-3 tháng, nếu gây tai nạn 2-4 tháng");
        loi_vi_pham.setCT_Loi("Không tuân thủ các quy định khi vào hoặc ra đường cao tốc; điều khiển xe chạy ở làn dừng xe khẩn cấp hoặc phần lề đường của đường cao tốc; chuyển làn đường không đúng nơi cho phép hoặc Không có tín hiệu báo trước khi chạy trên đường cao tốc; quay đầu xe, lùi xe trên đường cao tốc; không tuân thủ quy định về khoảng cách an toàn đối với xe chạy liền trước khi chạy trên đường cao tốc");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(101);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Vượt xe sai quy định");
        loi_vi_pham.setMuc_Phat("2.000.000 - 3.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Vuot xe sai quy dinh");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 1-3 tháng");
        loi_vi_pham.setCT_Loi("Vượt trong các trường hợp cấm vượt; Không có báo hiệu trước khi vượt; vượt bên phải xe khác trong trường hợp không được phép, trừ trường hợp tại đoạn đường có nhiều làn đường cho xe đi cùng chiều được phân biệt bằng vạch kẻ phân làn đường mà xe chạy trên làn đường bên phải chạy nhanh hơn xe đang chạy trên làn đường bên trái");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(102);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Tránh, nhường xe ngược chiều không đúng quy định");
        loi_vi_pham.setMuc_Phat("2.000.000 - 3.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Tranh, nhuong xe nguoc chieu khong dung quy dinh");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Tránh xe đi ngược chiều không đúng quy định; không nhường đường cho xe đi ngược chiều theo quy định tại nơi đường hẹp, đường dốc, nơi có chướng ngại vật;");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(103);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không nhường đường cho xe ưu tiên");
        loi_vi_pham.setMuc_Phat("2.000.000 - 3.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong nhuong duong cho xe uu tien");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 1-3 tháng");
        loi_vi_pham.setCT_Loi("Không nhường đường hoặc gây cản trở xe được quyền ưu tiên đang phát tín hiệu ưu tiên đi làm nhiệm vụ;");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(104);
        loi_vi_pham.setID_Nhom_Loi(5);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Đi ngược chiều trên cao tốc");
        loi_vi_pham.setMuc_Phat("7.000.000 - 8.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Di nguoc chieu tren cao toc");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 4-6 tháng.");
        loi_vi_pham.setCT_Loi("Điều khiển xe đi ngược chiều trên đường cao tốc, trừ các xe ưu tiên đang đi làm nhiệm vụ khẩn cấp theo quy định;");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(105);
        loi_vi_pham.setID_Nhom_Loi(6);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Trong máu và hơi thở có cồn dưới 0.25ml/l khi");
        loi_vi_pham.setMuc_Phat("2.000.000 - 3.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Trong mau va hoi tho co con duoi 0.25");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn");
        loi_vi_pham.setCT_Loi("Điều khiển xe trên đường mà trong máu hoặc hơi thở có nồng độ cồn nhưng chưa vượt quá 50 miligam/100 mililít máu hoặc chưa vượt quá 0,25 miligam/1 lít khí thở");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(106);
        loi_vi_pham.setID_Nhom_Loi(6);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Trong máu và hơi thở có cồn dưới 0.4ml/l khi");
        loi_vi_pham.setMuc_Phat("7.000.000 - 8.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Trong mau va hoi tho co con duoi 0.4");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 3-5 tháng");
        loi_vi_pham.setCT_Loi("Điều khiển xe trên đường mà trong máu hoặc hơi thở có nồng độ cồn vượt quá 50 miligam đến 80 miligam/100 mililít máu hoặc vượt quá 0,25 miligam đến 0,4 miligam/1 lít khí thở");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(107);
        loi_vi_pham.setID_Nhom_Loi(6);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Trong máu và hơi thở có cồn trên 0.4ml/l khi");
        loi_vi_pham.setMuc_Phat("16.000.000 - 18.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Trong mau va hoi tho co con duoi 0.4");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 4-6 tháng.");
        loi_vi_pham.setCT_Loi("Điều khiển xe trên đường mà trong máu hoặc hơi thở có nồng độ cồn vượt quá 80 miligam/100 mililít máu hoặc vượt quá 0,4 miligam/1 lít khí thở");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(108);
        loi_vi_pham.setID_Nhom_Loi(6);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không chấp hành kiểm tra nồng độ cồn");
        loi_vi_pham.setMuc_Phat("16.000.000 - 18.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong chap hanh kiem tra nong do con");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 4-6 tháng.");
        loi_vi_pham.setCT_Loi("Không chấp hành yêu cầu kiểm tra về nồng độ cồn của người thi hành công vụ");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(110);
        loi_vi_pham.setID_Nhom_Loi(6);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không chấp hành kiểm tra ma túy");
        loi_vi_pham.setMuc_Phat("16.000.000 - 18.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong chap hanh kiem tra ma tuy");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 4-6 tháng.");
        loi_vi_pham.setCT_Loi("Không chấp hành yêu cầu kiểm tra về chất ma túy của người thi hành công vụ");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(112);
        loi_vi_pham.setID_Nhom_Loi(6);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Sử dụng chất ma tuý");
        loi_vi_pham.setMuc_Phat("16.000.000 - 18.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Su dung chat ma tuy");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 22-24 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Điều khiển xe trên đường mà trong cơ thể có chất ma túy");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(113);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Điều khiển xe kéo rơ-moóc Không có biển báo hiệu");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dieu khien xe keo ro-mooc khong co bien bao hieu");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không gắn biển báo hiệu ở phía trước xe kéo, phía sau xe được kéo; điều khiển xe kéo rơ-moóc Không có biển báo hiệu theo quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(114);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Bấm còi sai quy định");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Bam coi sai quy dinh");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Bấm còi trong đô thị và khu đông dân cư trong thời gian từ 22 giờ ngày hôm trước đến 05 giờ ngày hôm sau, trừ các xe ưu tiên đang đi làm nhiệm vụ theo quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(115);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không thắt dây an toàn");
        loi_vi_pham.setMuc_Phat("100.000-200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong that day an toan");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Không thắt dây an toàn (tại vị trí có trang bị dây an toàn) khi xe đang chạy, Chở người trên xe ô tô không thắt dây an toàn (tại vị trí có trang bị dây an toàn) khi xe đang chạy");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(116);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Chở người quá quy định");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Cho nguoi qua quy dinh");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Chở người trên buồng lái quá số lượng quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(117);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Xe ưu tiên lắp đặt, sử dụng thiết bị phát tín hiệu ưu tiên không đúng quy định");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Xe uu tien lap dat, su dung thiet bi phat tin hieu uu tien khong dung quy dinh");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Xe được quyền ưu tiên lắp đặt, sử dụng thiết bị phát tín hiệu ưu tiên không đúng quy định hoặc sử dụng thiết bị phát tín hiệu ưu tiên mà Không có giấy phép của cơ quan có thẩm quyền cấp hoặc có giấy phép của cơ quan có thẩm quyền cấp nhưng không còn giá trị sử dụng theo quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(118);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Gây tai nạn không dừng lại");
        loi_vi_pham.setMuc_Phat("300.000-400.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Gay tai nan khong dung lai");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Điều khiển xe có liên quan trực tiếp đến vụ tai nạn giao thông mà không dừng lại, không giữ nguyên hiện trường, không tham gia cấp cứu người bị nạn");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(119);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Bấm còi, rú ga, sử dụng đèn chiếu xa không đúng quy định");
        loi_vi_pham.setMuc_Phat("600.000-800.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Bam coi, ru ga, su dung den chieu xa khong dung quy dinh");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Bấm còi, rú ga liên tục; bấm còi hơi, sử dụng đèn chiếu xa trong đô thị, khu đông dân cư, trừ các xe ưu tiên đang đi làm nhiệm vụ theo quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(120);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Sử dụng đèn chiếu sang không đúng quy định");
        loi_vi_pham.setMuc_Phat("600.000-800.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Su dung den chieu sang khong dung quy dinh");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Không sử dụng hoặc sử dụng không đủ đèn chiếu sáng trong thời gian từ 19 giờ ngày hôm trước đến 05 giờ ngày hôm sau, khi sương mù, thời tiết xấu hạn chế tầm nhìn; sử dụng đèn chiếu xa khi tránh xe đi ngược chiều");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(121);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Điều khiển xe kéo rơ moóc không nối chắc chắn, an toàn");
        loi_vi_pham.setMuc_Phat("600.000-800.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Dieu khien xe keo ro mooc khong noi chac chan, an toan");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 1-3 tháng, Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Điều khiển xe ô tô kéo theo xe khác, vật khác (trừ trường hợp kéo theo một rơ moóc, sơ mi rơ moóc hoặc một xe ô tô, xe máy chuyên dùng khác khi xe này không tự chạy được); điều khiển xe ô tô đẩy xe khác, vật khác; điều khiển xe kéo rơ moóc, sơ mi rơ moóc kéo thêm rơ moóc hoặc xe khác, vật khác; không nối chắc chắn, an toàn giữa xe kéo và xe được kéo khi kéo nhau");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(122);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Chở người trên xe được kéo");
        loi_vi_pham.setMuc_Phat("600.000-800.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Cho nguoi tren xe duoc keo");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 1-3 tháng");
        loi_vi_pham.setCT_Loi("Chở người trên xe được kéo, trừ người điều khiển");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(123);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Sử dụng điện thoại khi lái xe");
        loi_vi_pham.setMuc_Phat("600.000-800.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Su dung dien thoai khi lai xe");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Dùng tay sử dụng điện thoại di động khi đang điều khiển xe chạy trên đường");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(124);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không bật đèn chiếu sáng gần, lùi xe, quay đầu xe, vượt xe trong hầm đường bộ");
        loi_vi_pham.setMuc_Phat("800.000-1.200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong bat den chieu sang gan, lui xe, quay dau xe, vuot xe trong ham duong bo");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn giao thông");
        loi_vi_pham.setCT_Loi("Chạy trong hầm đường bộ không sử dụng đèn chiếu sáng gần; lùi xe, quay đầu xe trong hầm đường bộ; vượt xe trong hầm đường bộ không đúng nơi quy định");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(125);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Sử dụng thiết bị phát tín hiệu của xe ưu tiên");
        loi_vi_pham.setMuc_Phat("800.000-1.200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Su dung thiet bi phat tin hieu cua xe uu tien");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 1-3 tháng, nếu gây tai nạn 2-4 tháng");
        loi_vi_pham.setCT_Loi("Xe không được quyền ưu tiên lắp đặt, sử dụng thiết bị phát tín hiệu của xe được quyền ưu tiên");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(126);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không có biện pháp an toàn khi ôtô hư hỏng nơi giao nhau đường sắt");
        loi_vi_pham.setMuc_Phat("800.000-1.200.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong co bien phap an toan khi oto hu hong noi giao nhau duong sat");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 1-3 tháng, nếu gây tai nạn 2-4 tháng");
        loi_vi_pham.setCT_Loi("Không thực hiện biện pháp bảo đảm an toàn theo quy định khi xe ô tô bị hư hỏng ngay tại nơi đường bộ giao nhau cùng mức với đường sắt");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(127);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không tuân thủ người điều khiển giao thông");
        loi_vi_pham.setMuc_Phat("1.200.000 -2.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong tuan thu nguoi dieu khien giao thong");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng nếu gây tai nạn");
        loi_vi_pham.setCT_Loi("Không chấp hành hiệu lệnh, hướng dẫn của người điều khiển giao thông hoặc người kiểm soát giao thông.");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(128);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Gây tai nạn giao thông nhưng bỏ trốn, không giữ hiện trường");
        loi_vi_pham.setMuc_Phat("5.000.000 - 6.000.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("Gay tai nan giao thong nhung bo tron, khong giu hien truong");
        loi_vi_pham.setHp_BS("Tước giấy phép lái xe 2-4 tháng");
        loi_vi_pham.setCT_Loi("Gây tai nạn giao thông không dừng lại, không giữ nguyên hiện trường, bỏ trốn không đến trình báo với cơ quan có thẩm quyền, không tham gia cấp cứu người bị nạn");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(130);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("OTO");
        loi_vi_pham.setTen_Loi("Không có hoặc không mang theo Giấy chứng nhận bảo hiểm trách nhiệm dân sự của chủ xe cơ giới còn hiệu lực");
        loi_vi_pham.setMuc_Phat("400.000 - 600.000 vnđ");
        loi_vi_pham.setTen_Loi_Ko_Dau("khong co hoac khong mang theo Giay chung nhan bao hiem trach nhiem dan su cua chu xe co gioi con hieu luc");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Không mang bảo hiểm trách nhiệm dân sự  hoặc hết hiệu lực");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
        loi_vi_pham.setID(132);
        loi_vi_pham.setID_Nhom_Loi(7);
        loi_vi_pham.setPhuong_Tien("XM");
        loi_vi_pham.setTen_Loi("Không bật đèn xe( từ 18h-6h hoặc sương mù, thời tiết hạn chế tầm nhìn)");
        loi_vi_pham.setMuc_Phat("600.000-800.000 vnd");
        loi_vi_pham.setTen_Loi_Ko_Dau("Khong bat den xe( tu 18h-6h hoac suong mu, thoi tiet han che tam nhin)");
        loi_vi_pham.setHp_BS("Không có");
        loi_vi_pham.setCT_Loi("Không bật đèn xe trong thời gian quy định (18h-6h");
        databaseHandler.addLoi_Vi_Pham(loi_vi_pham);
    }
}
